"""pymumble 在新版 Python 上的兼容补丁。

pymumble 1.6.1 建 TLS 用的是 `ssl.wrap_socket()`——这个函数 Python 3.7 起弃用、
**3.12 已经删除**。而它那段调用长这样（mumble.py 的 connect）：

    try:
        self.control_socket = ssl.wrap_socket(...)          # 3.12 上抛 AttributeError
    except AttributeError:
        self.control_socket = ssl.wrap_socket(..., ssl.PROTOCOL_TLSv1)   # 同一个函数，再抛一次

兜底分支调的是同一个已被删除的函数，所以异常直接冲出去。又因为这一切发生在
pymumble 自己的线程里，调用方只看到"线程没了"，界面上就显示成"服务器拒绝了
连接"——把人往密码上引，而实际上连 TLS 握手都没开始（服务器日志里只会看到
连上又立刻断开）。

这里补一个等价实现。Mumble 用的是自签证书，CA 链校验对它没有意义——官方客户端
认的是**证书指纹**。所以这里 `check_hostname=False` + `CERT_NONE`，然后自己按
指纹认（见下面 PINNED_FINGERPRINTS）。

**这一段以前只写了前半句。** 注释拿"官方客户端靠指纹认"当理由，把校验整个关掉
就完事了，而指纹校验谁也没做——pymumble 自己也不做。于是论据的两半都不成立：
既没有 CA 链，也没有指纹，任何能插到中间的人握个手就能拿到接下来那条
`Authenticate`。而那条消息里的 password 是成员的**网站密码**（can-api 的
`VerifyNetworkCredential` 两个列都认，注册和改密写的是同一个），拿到就是整个账号。
现在指纹是真的在验了。

时序是关键，而且刚好留了位置（pymumble 1.6.1 `mumble.py` 的 `connect`）：

    self.control_socket = ssl.wrap_socket(std_sock, ...)   # 这时还没连上
    self.control_socket.connect((self.host, self.port))    # 握手在这里
    self.control_socket.setblocking(False)
    self.send_message(VERSION, ...)
    self.send_message(AUTHENTICATE, ...)                   # 密码在这里才出去

先包、后连，所以**握手发生在 socket 的 `connect()` 里**，而密码要到两行之后才
发。把校验放在 `connect()` 返回之前，就卡在这两者中间：验不过就抛，一个字节的
凭据都不会出去。放在 `Mumble.connect()` 外面包一层是不行的——那时候
`Authenticate` 早发完了。
"""

import hashlib
import logging
import os
import select
import ssl
import time

log = logging.getLogger("mumblecompat")

# ---- 服务器证书指纹 ----

# 官方语音服务器。只有连它的时候才强制校验指纹：xpc/msfs 的 mumble_host 是可以
# 改的，成员把客户端指到自建服务器或者内网镜像是当真的（CLAUDE.md 里写着），
# 不能因为指纹对不上就把人挡在外面。指到别处时只把指纹记一行 INFO。
PINNED_HOST = "audio.ceruleanavi.net"

# audio.ceruleanavi.net 的证书指纹（SHA-256，小写十六进制，不带冒号）。
#
# Murmur 自签，CN=Murmur Autogenerated Certificate v2，2026-08-04 签发、
# 2046-07-30 到期。两条 A 记录（116.62.139.121 / 208.68.182.85）给的是同一张
# 证书，实测比对过，所以走哪条都认得出来。
#
# 重新取：
#     openssl s_client -connect audio.ceruleanavi.net:64738 </dev/null \
#         | openssl x509 -noout -fingerprint -sha256
#
# **写成元组是为了换证书那一次。** Murmur 的证书存在
# /var/lib/mumble-server 的 sqlite 里；那个卷要是没了，服务器会重新自签一张，
# 于是所有已经发出去的客户端全部连不上，而且没有任何办法远程修。换证书的做法
# 是：先发一版**同时收下新旧两个**指纹，等大家都更新了再把旧的删掉。急救口子
# 是下面那个环境变量。
PINNED_FINGERPRINTS = (
    "b7b66eeb91d4a1044039263d1a1e10e179cd09abc1664e754c5a3f11c5bb331a",
)

# 急救/自建用：逗号或空格分隔，允许带冒号，大小写随意。设了就完全取代上面那
# 组。留空等于没设——不是"清空指纹"，否则一个空环境变量就成了绕过的开关。
FINGERPRINT_ENV = "CAN_MUMBLE_FINGERPRINTS"


class CertificatePinError(Exception):
    """服务器证书和钉住的指纹对不上。

    **故意不继承 OSError。** pymumble 的 `connect()` 里那段 `except
    socket.error`（就是 OSError）会把它吞成"连接失败"，然后 BoundedReconnect
    再试三次——而中间人重试三次还是中间人，只是把一条本该刺眼的记录冲淡成三条
    普通的网络错误。不是 OSError 就会直接穿出 `Mumble.connect()`，谁也拦不住。
    """


def normalise_fingerprint(value):
    """`B7:B6:…` / `b7b66e…` / 带空格的，统一成小写无分隔。"""
    return "".join(str(value or "").split()).replace(":", "").replace("-", "").lower()


def certificate_fingerprint(der):
    """DER 编码的证书 → SHA-256 指纹（小写十六进制）。"""
    return hashlib.sha256(der).hexdigest() if der else ""


def accepted_fingerprints():
    """这次连接认哪些指纹。环境变量设了就用它，否则用源码里那组。"""
    raw = (os.environ.get(FINGERPRINT_ENV) or "").replace(",", " ").split()
    override = tuple(f for f in map(normalise_fingerprint, raw) if f)
    return override or tuple(f for f in map(normalise_fingerprint,
                                            PINNED_FINGERPRINTS) if f)


def is_pinned_host(host):
    """这个主机名要不要按指纹校验。"""
    name = str(host or "").strip().rstrip(".").lower()
    return name == PINNED_HOST


def check_certificate(host, der):
    """握手完了验指纹。对不上就抛 CertificatePinError。返回看到的指纹。

    纯函数（除了记日志），所以测试不需要真的建 TLS 连接。
    """
    seen = certificate_fingerprint(der)

    if not is_pinned_host(host):
        # 自建服务器 / 内网镜像 / 直接填 IP。把指纹记下来，想钉的人有的可钉。
        log.info("voice server %s presented certificate SHA-256 %s "
                 "(not the pinned host, fingerprint not enforced)",
                 host or "(unknown)", seen or "(unavailable)")
        return seen

    accepted = accepted_fingerprints()
    if not accepted:
        # 只有把源码里那组常量清空才会走到这里，属于构建期的失误。为它把所有
        # 人的语音一起停掉不划算，但必须吵。
        log.warning("no pinned fingerprint is configured, so the certificate of "
                    "%s (SHA-256 %s) was not checked", host, seen or "(unavailable)")
        return seen

    if seen and seen in accepted:
        log.debug("voice server certificate matches the pin (SHA-256 %s)", seen)
        return seen

    log.error("refusing to log in to %s: its certificate SHA-256 is %s, which is "
              "not pinned. The network password is sent on this connection, so "
              "it is not being sent. If the server certificate was replaced on "
              "purpose, ship the new fingerprint or set %s.",
              host, seen or "(unavailable)", FINGERPRINT_ENV)
    raise CertificatePinError(
        f"the certificate of {host} (SHA-256 {seen or 'unavailable'}) is not "
        f"one of the pinned fingerprints")


def verify_peer(sock, addr):
    """握手完的 socket + 它连的地址 → 验指纹，不过就关掉并抛。

    单独拿出来是为了能测：造一个有 `getpeercert`/`close` 的替身就行，不用真的
    起一个 TLS 服务器。
    """
    host = addr[0] if isinstance(addr, (tuple, list)) and addr else addr
    try:
        der = sock.getpeercert(binary_form=True)
    except Exception as e:
        # CERT_NONE 下 getpeercert(binary_form=True) 照样给 DER，拿不到就是真
        # 出事了。当成对不上处理，绝不能当成"没检查所以放行"。
        log.error("could not read the certificate of %s: %s", host, e)
        der = None
    try:
        return check_certificate(host, der)
    except Exception:
        # TLS 是建起来了，但这条连接不能用。自己关掉，别留一条谁都以为还能
        # 用的 socket。
        try:
            sock.close()
        except Exception:
            pass
        raise

# 发不动时最多等多久再判定为真的断了。等待期间 pymumble 的主循环是停着的
# （收不到别人的话音），所以不能太长；但比起丢连接重连（实测五秒起步，还要重新
# 进频道）又划算得多。
SEND_TIMEOUT = 2.0


class _SendStats:
    """上行堵了多少次、最久一次等了多久。

    单独统计而不是每次都记日志：上行紧张时一秒能进几十次重试，逐条记只会把
    真正的线索淹掉。调用方（voice.py / broadcast.py）在掉线时和定期各取一次
    汇总——**「掉线前这一分钟堵过 37 次、最久 0.8 秒」比任何一行流水都说明问题**，
    它直接区分了"上行真的不行"和"只是一次瞬时抖动"。
    """

    def __init__(self):
        self.blocked = 0          # 写不动过多少次
        self.gave_up = 0          # 其中彻底放弃（判定断线）的次数
        self.worst = 0.0          # 最久的一次等待
        self.total = 0.0          # 累计等待时间

    def record(self, waited, gave_up=False):
        self.blocked += 1
        self.total += waited
        self.worst = max(self.worst, waited)
        if gave_up:
            self.gave_up += 1

    def drain(self):
        """取走并清零。返回 None 表示这段时间一次都没堵过。"""
        if not self.blocked:
            return None
        summary = (f"the send buffer was full {self.blocked} time(s) "
                   f"(worst {self.worst * 1000:.0f} ms, {self.total:.1f} s total"
                   + (f", {self.gave_up} of them gave up" if self.gave_up else "")
                   + ")")
        self.__init__()
        return summary


_stats = _SendStats()


def send_stats():
    """取走自上次调用以来的上行拥塞汇总，没有就返回 None。"""
    return _stats.drain()


class _RetryingSocket:
    """给非阻塞 socket 的 `send()` 补上"等它可写再续发"。

    **这是语音"一发话就掉线"的病根。** pymumble 没有 UDP 通道：话音被塞进
    `UDPTUNNEL` 消息，和控制消息走**同一条 TCP**（soundoutput.py 的
    `tcppacket = ... # encapsulate in tcp tunnel`）。而那条 socket 在
    `connect()` 里被设成了非阻塞，发送循环却是照 C 的写法兜错的：

        sent = self.mumble_object.control_socket.send(tcppacket)
        if sent < 0:                     # Python 里 send 是抛异常，不是返回 -1
            raise socket.error(...)

    于是上行稍微堵一下、内核发送缓冲一满，`send()` 抛 `BlockingIOError`
    （TLS 上是 `SSLWantWriteError`），一路穿到 `Mumble.run()` 的
    `except socket.error`，连接被判死、DISCONNECTED 发出去——**而网络上其实
    什么都没断**。实测日志里的形状正是这样：掉线都发生在按下 PTT 两三秒后，
    0.2 秒的短发话从不掉，而且每次都是第一次重连就立刻成功。

    这一层只改"写不动"这一种情况：等这条 socket 可写再续发，等满
    SEND_TIMEOUT 才把异常放出去（那时候是真的堵死了，当断线处理是对的）。
    部分写入不用管——pymumble 两处发送循环本来就按返回值切片重发。
    """

    def __init__(self, sock, timeout=SEND_TIMEOUT):
        self._sock = sock
        self._timeout = timeout

    def __getattr__(self, name):
        # recv / close / fileno / getpeercert … 一律原样转交。select.select()
        # 认 fileno()，所以主循环那句 select 照常工作。
        return getattr(self._sock, name)

    def send(self, data):
        deadline = time.monotonic() + self._timeout
        waited = 0.0
        while True:
            try:
                sent = self._sock.send(data)
                if waited:
                    # 只统计，不每次都打日志——上行紧张时这里一秒能进几十次，
                    # 记成日志反而把真正的线索淹掉。汇总由调用方定期打印。
                    _stats.record(waited)
                return sent
            except (BlockingIOError, ssl.SSLWantWriteError) as e:
                error, readable = e, False
            except ssl.SSLWantReadError as e:
                # TLS 在重新协商时会要求先读到东西才写得出去
                error, readable = e, True

            remaining = deadline - time.monotonic()
            if remaining <= 0:
                _stats.record(waited, gave_up=True)
                log.warning("the control socket stayed unwritable for %.0f s, "
                            "treating it as a lost connection", self._timeout)
                raise error

            started = time.monotonic()
            if readable:
                select.select([self._sock], [], [], remaining)
            else:
                select.select([], [self._sock], [], remaining)
            waited += time.monotonic() - started


def guard_control_socket(mumble):
    """把某个 Mumble 对象的控制 socket 换成会重试的那个。

    幂等：已经换过就不再套一层。
    """
    sock = getattr(mumble, "control_socket", None)
    if sock is None or isinstance(sock, _RetryingSocket):
        return False
    mumble.control_socket = _RetryingSocket(sock)
    return True


def patch_send():
    """让每一条新建的连接都自动带上上面那层。返回是否真的打了补丁。

    挂在 `Mumble.connect()` 之后而不是让每个客户端自己去包：连接是 pymumble
    在**它自己的线程里**建的，而且每次重连都会重建一次 socket——漏掉任何一次
    重连，那条连接就退回旧行为，而症状（发话时掉线）只在网络不好的用户那里出现，
    自己这边根本复现不了。
    """
    try:
        from pymumble_py3.mumble import Mumble
    except Exception as e:                       # 打包环境里理论上不会发生
        log.warning("could not patch the pymumble send path: %s", e)
        return False

    if getattr(Mumble.connect, "_can_guarded", False):
        return False

    original = Mumble.connect

    def connect(self):
        state = original(self)
        try:
            guard_control_socket(self)
        except Exception as e:
            # 包不上就照旧跑，只是会退回"发不动就掉线"的老行为
            log.warning("could not guard the control socket: %s", e)
        return state

    connect._can_guarded = True
    Mumble.connect = connect
    log.info("patched pymumble so a full send buffer no longer looks like a "
             "lost connection")
    return True


class _PinnedSSLSocket(ssl.SSLSocket):
    """握手一完就验指纹，验不过不让 `connect()` 返回。

    pymumble 是**先包后连**，所以握手在这个 `connect()` 里发生，而
    `Authenticate`（带着成员的网站密码）要到调用方的两行之后才发。抛在这里，
    密码就一个字节都没出去。

    做成 `ssl.SSLSocket` 的子类而不是套一层代理，是因为下游要拿它当真 socket
    用：pymumble 的主循环 `select.select([control_socket], …)`，`_RetryingSocket`
    还要再包一层，测试里也 `assertIsInstance(..., ssl.SSLSocket)`。
    `SSLContext.sslsocket_class` 就是标准库留给这件事的口子。
    """

    def connect(self, addr):
        result = super().connect(addr)
        verify_peer(self, addr)
        return result

    def connect_ex(self, addr):
        result = super().connect_ex(addr)
        if result == 0:
            verify_peer(self, addr)
        return result


def install():
    """打上 pymumble 需要的两个补丁。返回值只说 ssl.wrap_socket 补没补。

    发送那个补丁在这里一并打上：所有客户端都在 import pymumble **之前**调
    install()，这是唯一一处四个组件都必经的地方。
    """
    patched_ssl = _install_wrap_socket()
    if not patched_ssl and not getattr(ssl.wrap_socket, "_can_pinned", False):
        # 只可能发生在 3.12 以前——那里 ssl.wrap_socket 还在，我们不去动它
        # （动了会连累进程里别的东西），于是指纹校验也就挂不上。仓库要求
        # Python 3.12、CI 也钉死 3.12，所以发出去的包都走上面那条路；这行是
        # 给在旧解释器上跑源码的人看的，免得以为钉住了。
        log.warning("this Python still has ssl.wrap_socket, so the voice server "
                    "certificate is NOT pinned; use Python 3.12 or newer")
    patch_send()
    return patched_ssl


def _install_wrap_socket():
    """需要的话补上 ssl.wrap_socket。返回是否真的打了补丁。

    补回来的这一份同时是**指纹校验挂靠的地方**（`_PinnedSSLSocket`），不再只是
    一个兼容垫片。
    """
    if hasattr(ssl, "wrap_socket"):
        return False

    def wrap_socket(sock, keyfile=None, certfile=None, cert_reqs=ssl.CERT_NONE,
                    ca_certs=None, **kwargs):
        # 忽略调用方传进来的 ssl_version：那些常量在新版里也已弃用，
        # 交给 SSLContext 自己协商更稳妥
        context = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
        # 顺序不能反：check_hostname 还是 True 时设 CERT_NONE 会抛 ValueError
        context.check_hostname = False
        context.verify_mode = cert_reqs
        if ca_certs:
            context.load_verify_locations(ca_certs)
        if certfile:
            context.load_cert_chain(certfile, keyfile)
        # CA 链认不了自签证书，认的是指纹——由这个子类在握手之后、发
        # Authenticate 之前做
        context.sslsocket_class = _PinnedSSLSocket
        return context.wrap_socket(sock)

    wrap_socket._can_pinned = True
    ssl.wrap_socket = wrap_socket
    log.info("reinstated ssl.wrap_socket for pymumble (removed from Python "
             "3.12 onwards); the voice server certificate is pinned by "
             "SHA-256 fingerprint")
    return True
